name: workflow-1

on:
  push:
    branches:
    - '*'


jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["env1", "env2"]
        regions: ["us1", "asia2", "europe3"]
      max-parallel: 1
    steps:
      - name: step1
        run: | 
          echo "${{ matrix.env }}"
      - name: test
        run: |
          echo "${{ matrix.regions }}"
