name: workflow-1

on:
  push:
    branches:
    - '*'


jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["env1", "env2"]
    steps:
      - name: step1
        run: | 
          echo "step1"
