name: workflow-1

on:
  push:
    branches:
    - '*'
    branches-ignore:
    - 'test'


jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: | 
          echo "step1"
